#debug: true

spring:
  devtools:
    restart:
      enabled: true #页面开启热部署
  freemarker:
    cache: false #页面不加载缓存，修改即时生效
  data:
    elasticsearch:
      repositories:
        enabled: true
      cluster-name: docker-cluster
      cluster-nodes: 10.156.196.229:9300
  elasticsearch:
    rest:
      uris: http://10.156.196.229:9200


  jackson:
    time-zone: GMT+8  #市区设置

  datasource:
    url: jdbc:mysql://10.156.196.227:3306/his?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
    username: root
    password: admin
    druid:
      initial-size: 5 #连接池初始化大小
      min-idle: 10 #最小空闲连接数
      max-active: 20 #最大连接数
      web-stat-filter:
        exclusions: "*.js,*.gif,*.jpg,*.png,*.css,*.ico,/druid/*" #不统计这些请求数据
      stat-view-servlet: #访问监控网页的登录用户名和密码
        login-username: druid
        login-password: druid


