spring:
  application:
    name: his-cloud-config
  cloud:
    config:
      label: master
      server:
        git:
          uri: https://github.com/ZainZhao/spring-cloud-config
          search-paths: respo
          username: ZainZhao
          password: 
          force-pull: true
#  rabbitmq:
#    host: localhost
#    port: 5672
#    username: guest
#    password: guest
  boot:
    admin:
      client:
        url: http://localhost:8084

  zipkin:
    base-url: http://localhost:9411

  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest


server:
  port: 8888  #只能在bootstrap中才能呢个改

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

management:
  endpoints:
    web:
      exposure:
        include: "*"   #暴露所有的端点我们可以看到更多的服务实例相关信息，
    endpoint:
      health:
        show-details: ALWAYS   #health endpoint是否必须显示全部细节